export const errorCodes = {
  required: 'required',
  invalidType: 'invalid_type',
  invalidEnum: 'invalid_enum',
  invalidInteger: 'invalid_integer',
  invalidArrayItems: 'invalid_array_items',
  invalidObject: 'invalid_object',
  invalidObjectShape: 'invalid_object_shape',
  invalidUnion: 'invalid_union',
  invalidISODate: 'invalid_iso_date',
  invalidISOTime: 'invalid_iso_time',
  invalidISODatetime: 'invalid_iso_datetime',
  invalidNumericString: 'invalid_numeric_string',
  stringTooShort: 'string_too_short',
  stringTooLong: 'string_too_long',
  stringPattern: 'string_pattern',
  emptyString: 'empty_string',
  numberTooSmall: 'number_too_small',
  numberTooLarge: 'number_too_large',
  numberOutOfRange: 'number_out_of_range',
  arrayTooShort: 'array_too_short',
  arrayTooLong: 'array_too_long',
};
