export const errorCodes = {
  required: 'required',
  invalidType: 'invalid_type',
  invalidEnum: 'invalid_enum',
  invalidArrayItems: 'invalid_array_items',
  invalidObject: 'invalid_object',
  invalidObjectShape: 'invalid_object_shape',
  invalidUnion: 'invalid_union',
  invalidISODate: 'invalid_iso_date',
  invalidISOTime: 'invalid_iso_time',
  invalidISODatetime: 'invalid_iso_datetime',
  invalidNumericString: 'invalid_numeric_string',
  stringTooLong: 'string_too_long',
  stringTooShort: 'string_too_short',
  stringPattern: 'string_pattern',
  numberTooSmall: 'number_too_small',
};
